namespace Specforge.Core.Init;

/// <summary>
/// Produces the minimal Codex project-level <c>agents/openai.yaml</c> declaring specforge as an MCP
/// dependency (DEC-005 boundary — owned by <c>init</c>, not <c>install_skills</c>).
/// </summary>
public sealed class CodexOpenaiYamlWriter
{
    /// <summary>The canonical YAML content.</summary>
    public string Generate() =>
        string.Join('\n',
        [
            "# Generated by specforge init. Declares specforge as a project-level MCP server for Codex.",
            "mcp_servers:",
            "  specforge:",
            "    command: specforge",
        ]) + "\n";
}
