using System.Text;

using Specforge.Core.Configuration;
using Specforge.Core.Diagnostics;

namespace Specforge.Core.Init;

/// <summary>
/// Renders <c>SPECFORGE.md</c> from the live config (DEC-008 section template). specforge-owned;
/// always regenerated on <c>init</c>.
/// </summary>
public sealed class SpecforgeMdGenerator(BinaryInfo binaryInfo)
{
    // DEC-007 MVP tool catalog (21) and DEC-008 skill catalog (7) — static lists fixed by the DECs.
    private static readonly string[] Tools =
    [
        "init", "install_skills", "list_packages", "use_package", "info",
        "list_decisions", "get_decision", "create_decision", "set_decision_status", "delete_decision",
        "list_items", "get_item", "create_item", "set_item_status", "delete_item",
        "append_history", "append_review", "append_commit", "delete_review", "delete_commit",
        "validate",
    ];

    private static readonly string[] Skills =
    [
        "draft-decision", "review-decision", "draft-item", "review-item",
        "impact-assessment", "validate-spec-graph", "adopt-existing-project",
    ];

    /// <summary>Generates the full <c>SPECFORGE.md</c> body.</summary>
    public string Generate(SpecforgeConfig config, string projectName, string generatedOn)
    {
        ArgumentNullException.ThrowIfNull(config);

        StringBuilder builder = new();
        builder.Append($"# SPECFORGE — Spec-Driven Workspace for `{projectName}`\n\n");

        builder.Append("## Spec layout\n");
        foreach (SpecforgePackageConfig package in config.Packages)
        {
            string extras = package.ExtraKinds.Count == 0 ? string.Empty : $" (extra kinds: {string.Join(", ", package.ExtraKinds)})";
            builder.Append($"- Package `{package.Name}` at `{package.Path}`{extras}\n");
        }

        builder.Append($"- Shared docs: `{config.Shared}/`\n");
        builder.Append($"- Templates: `{config.Templates}/`\n");
        builder.Append($"- Active package selection: {(config.Packages.Count == 1 ? "single-package auto-select" : "multi-package via `use_package`")}\n\n");

        IReadOnlyList<string> allExtras = [.. config.Packages.SelectMany(p => p.ExtraKinds).Distinct()];
        builder.Append("## Identifier scheme\n");
        builder.Append("- Core kinds: DEC, ITEM, ART, REV, CMT (per DEC-004)\n");
        builder.Append($"- Extra kinds declared for this project: {(allExtras.Count == 0 ? "none" : string.Join(", ", allExtras))}\n");
        builder.Append("- Bare references resolve inside the active package; cross-package references use `<package>/<id>`.\n\n");

        builder.Append("## Tools available\n");
        foreach (string tool in Tools)
        {
            builder.Append($"- `{tool}`\n");
        }

        builder.Append("\n## Skills available\n");
        foreach (string skill in Skills)
        {
            builder.Append($"- `{skill}`\n");
        }

        builder.Append($"\n## Lifecycle\nStates and transitions per `{config.Shared}/document_lifecycle.md`.\n\n");
        builder.Append($"## Generated by\n`init` on {generatedOn}; specforge binary version {binaryInfo.Version}; config schemaVersion {config.SchemaVersion}.\n");

        return builder.ToString();
    }
}
