using Specforge.Core.Configuration;
using Specforge.Core.Diagnostics;
using Specforge.Core.Init;

using Xunit;

namespace Specforge.Tests.Init;

public class SpecforgeMdGeneratorTests
{
    private static readonly SpecforgeMdGenerator Generator = new(new BinaryInfo());

    private static SpecforgeConfig Config(IReadOnlyList<string>? extraKinds = null) => new(
        1, "spec/shared", "spec/templates",
        [new SpecforgePackageConfig("specforge-mvp", "spec/packages/specforge-mvp", extraKinds ?? SpecforgePackageConfig.NoExtraKinds)],
        "/repo/.specforge.json");

    [Fact]
    public void Generate_ContainsAllSections()
    {
        string md = Generator.Generate(Config(), "specforge", "2026-05-29");

        Assert.Contains("# SPECFORGE — Spec-Driven Workspace for `specforge`", md, StringComparison.Ordinal);
        Assert.Contains("## Spec layout", md, StringComparison.Ordinal);
        Assert.Contains("## Identifier scheme", md, StringComparison.Ordinal);
        Assert.Contains("## Tools available", md, StringComparison.Ordinal);
        Assert.Contains("## Skills available", md, StringComparison.Ordinal);
        Assert.Contains("## Lifecycle", md, StringComparison.Ordinal);
        Assert.Contains("## Generated by", md, StringComparison.Ordinal);
        Assert.Contains("specforge-mvp", md, StringComparison.Ordinal);
        Assert.Contains("schemaVersion 1", md, StringComparison.Ordinal);
        Assert.Contains("2026-05-29", md, StringComparison.Ordinal);
        Assert.Contains("`init`", md, StringComparison.Ordinal);
        Assert.Contains("`validate`", md, StringComparison.Ordinal);
        Assert.Contains("`draft-decision`", md, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ListsExtraKinds()
    {
        string md = Generator.Generate(Config(["RDM"]), "specforge", "2026-05-29");
        Assert.Contains("RDM", md, StringComparison.Ordinal);
    }
}
